### ISSUE TITLE
Bug in FastAttention.forward()

### ISSUE THREAD

**Issue by shayeboshi** [lucidrains/performer-pytorch#27]
Line 171 to 174 of performer_pytorch.py, forward() creates a projection_matrix each time it runs, while saves the projection_matrix after creating it first. I think there should be a line between line 172 and 173:
`self.projection_matrix = projection_matrix`

**Comment by lucidrains** [comment]
@shayeboshi Hello! So it's supposed to redraw a projection matrix each time. The paper reports best results that way

It only saves the projection matrix if you explicitly set redraw to false or call it at the end of training, as shown in the advanced section of the readme

**Comment by norabelrose** [comment]
@lucidrains I understand what you're trying to do, but I think you are slightly misinterpreting the paper. On page 7, underneath figure 4, it says "To further improve overall approximation of attention blocks across multiple iterations which further improves training, random samples should be **periodically** redrawn."

I interpret this to mean, say, every 1-5k training steps. If you look at the graph on the right in Figure 5, it pretty clearly looks like they didn't redraw features until around 22k steps, noticed that they had plateaued, and then redrew at that point. I would recommend including a user-definable parameter "feature_redraw_interval," which would maybe default to 1k. FastAttention would keep track of how many times forward() is called, redraw the features when it hits the redraw interval, and then reset the counter.

I think this is especially important for computational efficiency, since redrawing the orthogonal features requires doing QR composition on the CPU once per layer, per forward pass.

By the way, thank you for your work bringing this to PyTorch— I'm working on a research project right now which will use an implementation of FAVOR+ that borrows heavily from yours. I plan to cite you if/when I publish.

**Comment by norabelrose** [comment]
Just implemented the suggestion and created a pull request

**Comment by lucidrains** [comment]
@norabelrose @shayeboshi ohh yes, I do believe I misunderstood the redrawing! accepting the PR, thank you!

**Comment by lucidrains** [comment]
https://github.com/lucidrains/performer-pytorch/commit/78d7aa11ed9b1b50a2d743064d274e39b3593823
